name: CI/CD Pipeline

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                node-version: 18
                cache: 'npm'

            - name: Install Dependencies
              run: npm install

            - name: Run Linter
              run: npm run lint

            - name: Run Tests
              run: npm test

            - name: Build Next.js App
              run: npm run build

    deploy:
        needs: build-and-test
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                node-version: 18
                cache: 'npm'

            - name: Install Dependencies
              run: npm install

            - name: Deploy to Vercel
              run: npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
            